name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: [self-hosted] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: |
          npm test > test-results.txt

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results.txt

  deploy:
    needs: test
    runs-on: [self-hosted]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: test-results

      - name: Show test results
        run: cat test-results.txt

      - name: Install dependencies
        run: npm install

      - name: Install PM2 globally
        run: npm install -g pm2

      - name: Stop existing app (if running)
        run: pm2 delete my-app || echo "App not running"

      - name: Start app with PM2
        run: pm2 start src/server.js --name my-app

      - name: Check if app is running
        run: curl -sSf http://localhost:3000 || (echo "App failed to start" && exit 1)

      - name: Show PM2 process list
        run: pm2 list

      - name: Save app logs
        run: pm2 logs my-app --lines 100 > pm2-log.txt

      - name: Upload PM2 logs
        uses: actions/upload-artifact@v4
        with:
          name: pm2-log
          path: pm2-log.txt
